input {
  file {
    path => "/usr/share/logstash/data_input/gold/anime_gold.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
  }
}

filter {
  csv {
    separator => ","
    skip_header => true
    autodetect_column_names => true
  }

  mutate {
    convert => {
      "MAL_ID" => "integer"
      "weighted_popularity_score" => "float"
      "dropped_completed_ratio" => "float"
      "synopsis_length" => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "anime_gold"
    document_id => "%{MAL_ID}"
  }
}