# ============================================
# Datasource Elasticsearch auto-configurée
# Les apprenants n'ont rien à faire !
# ============================================

apiVersion: 1

deleteDatasources:
  - name: Elasticsearch - Anime
    orgId: 1

datasources:
  - name: Elasticsearch - Anime
    uid: elasticsearch-anime
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "anime"
    isDefault: true
    editable: true
    jsonData:
      esVersion: "8.12.0"
      timeField: "@timestamp"
      interval: "Yearly"
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
      includeFrozen: false

  # Alias uid for compatibility with grafana-config-prof dashboards.
  - name: Elasticsearch - Anime (Alias)
    uid: anidata-es
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "anime"
    isDefault: false
    editable: true
    jsonData:
      esVersion: "8.12.0"
      timeField: "@timestamp"
      interval: "Yearly"
      logLevelField: ""
      logMessageField: ""
      maxConcurrentShardRequests: 5
      includeFrozen: false
